version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hospitality_user
      POSTGRES_PASSWORD: hospitality_pass
      POSTGRES_DB: hospitality_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospitality_user -d hospitality_scheduler"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: